sudo: false
language: ruby
rvm:
  - 2.2.5
before_install:
  - rvm @default,@global do gem uninstall bundler -a -x
  - gem install bundler -v 1.10.5
deploy:
  provider: rubygems
  api_key:
    secure: "ThMTLeJ1E2dLLAK1AIokfE+0GyfCKwaAstxETI/qFkOwL21REi6dgTfPIrBpgmrYATb/YgkgIf6Zl46R7vx9/dtgIGBmX7AXT3zsR38P3zfOGy5PzHGGK72ZmkC5UFSBsnQl5J0qQsUEMQfEy2g7dwn1d9aFLKhvnFblNHt4x5c="
  on:
    tags: true